name: Create Terraform Backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to use"
        required: true
        type: choice
        options:
          - dev
          - prd

jobs:
  create-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Make script executable
        run: chmod +x cicd/scripts/create_backend.sh

      - name: Run backend script
        run: ./cicd/scripts/create_terraform_backend.sh
        env:
          backend_bucket: ${{ secrets.BACKEND_BUCKET }}
          backend_dynamodb_table: ${{ secrets.BACKEND_DYNAMODB_TABLE }}
          aws_region: ${{ secrets.AWS_REGION }}
