name: Create Terraform Backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to use"
        required: true
        type: choice
        options:
          - DEV
          - PRD

permissions:
  id-token: write
  contents: read

jobs:
  create-backend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Make script executable
        run: chmod +x cicd/scripts/create_terraform_backend.sh

      - name: Run backend script
        run: ./cicd/scripts/create_terraform_backend.sh
        env:
          backend_bucket: ${{ vars.BACKEND_BUCKET }}
          backend_dynamodb_table: ${{ vars.BACKEND_DYNAMODB_TABLE }}
          aws_region: ${{ vars.AWS_REGION }}
      - name: Create ECR repository if needed
        run: |
          if aws ecr describe-repositories --repository-names "$ECR_REPO" --region "$AWS_REGION" 2>/dev/null; then
            echo "[INFO] ECR repository already exists: $ECR_REPO"
          else
            echo "[INFO] Creating ECR repository: $ECR_REPO"
            aws ecr create-repository \
              --repository-name "$ECR_REPO" \
              --image-scanning-configuration scanOnPush=true \
              --region "$AWS_REGION"
            fi
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          ECR_REPO: ${{ vars.ECR_REPO }}
